services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: company-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - backend

  company-service:
    build: ./company-service
    container_name: company-service
    depends_on:
      - postgres
      - discovery-service
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - postgres
      - discovery-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
