services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: company_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=api-gateway
    ports:
      - "8080:8080"
    networks:
      - backend


  company-service:
    build: ./company-service
    container_name: company-service
    depends_on:
      - postgres
      - discovery-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/company
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=company-service
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - postgres
      - discovery-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=user-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
